# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20180313_0103'),
        ('note', '0002_auto_20180313_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reference',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reference.Reference'),
            preserve_default=False,
        ),
    ]
