version: '3'

services:

  django:
    build: .
    command: python phdnotes/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: 'postgres:10.2'
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - './data:/var/lib/postgresql/data/'
