# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='Source',
            new_name='source',
        ),
    ]
